### ISSUE TITLE
Преимущества по сравнению с AES

### ISSUE THREAD

**Issue by AndrewB330** [zoresvit/kalyna-c#1]
Не знаю где лучше задать вопрос, поэтому спрошу тут. 
А в чем преимущества данного шифра по сравнению AES? В частности, версии 128/128 против AES128?

**Comment by rkiyanchuk** [comment]
@AndrewB330 Обґрунтування  дизайну шифру, цілі та вимоги, які ставили перед собою автори під час розробки, описані в публікації [Results of Ukrainian National Public Cryptographic Competition](https://www.sav.sk/journals/uploads/0317154006ogdr.pdf):

>  General requirement to “Kalyna” is to have very high level of cryptographic security providing acceptable implementation characteristics. Modifications of Rijndael construction decreased the speed of the cipher (approximately to ∼ 85 % of AES on software implementations), complicated hardware and software implementations (especially on smart-cards), but protected algorithm from potential weaknesses of AES/Rijndael (like algebraic analysis [10], related-key cryptanalysis [11]) and provided very good security margin, especially for the block length and key size of 512 bits.

Ще деякі  подробиці, включаючи бенчмарки, є в презентації [Kalyna block cipher](https://www.slideshare.net/oliynykov/kalyna-english). 

> Не знаю где лучше задать вопрос, поэтому спрошу тут.

Також в [публікації](https://eprint.iacr.org/2015/650.pdf) на IACR є ще email-адреси кількох авторів 🙂
